#!/bin/bash
set -o nounset -o pipefail -o errexit

if ! command -v node &>/dev/null; then
    echo 'mdview: Node.js is not installed' >&2
    exit 127
fi

# Convert the paths to Windows format because Node doesn't understand Cygwin
if [ $# -eq 0 ]; then
    exec node "$(cygpath -w "$HOME/opt/mdview/bin/mdview")"
else
    exec node "$(cygpath -w "$HOME/opt/mdview/bin/mdview")" "$(cygpath -w "$1")"
fi
