#!/bin/bash
set -o errexit -o nounset -o pipefail

# Source: https://hostarina.com/Support/kb-article/81/how-to-count-inode-usage-in-linux-/
find "${1:-.}" -printf "%h\n" | cut -d/ -f-2 | sort | uniq -c | sort -rn
