#!/bin/bash

exe=vendor/bin/drush

if ! dir="$(findup -f $exe)"; then
    echo "You do not appear to be within a project with Drush installed ($exe)" >&2
    exit 1
fi

args=
if [ -f "$dir/www/includes/bootstrap.inc" ]; then
    args="--root=$dir/www"
fi

exec "$dir/$exe" $args "$@"
