#!/bin/bash

if [ $# == 0 ]; then
    du -sh -- *
else
    du -sh "$@"
fi | perl -e 'sub h{%h=(K=>10,M=>20,G=>30);($n,$u)=shift=~/([0-9.]+)(\D)/; return $n*2**$h{$u}}print sort{h($a)<=>h($b)}<>;'

# Reversed $a and $b at the end to get biggest last, and smallest will scroll off the screen

# http://serverfault.com/questions/62411/how-can-i-sort-du-h-output-by-size
#perl -e'%h=map{/.\s/;99**(ord$&&7)-$`,$_}`du -sh *`;print@h{sort%h}'
