#!/bin/bash

# Incoming and outgoing commits
help() {
    echo -e "\e[36m$1\e[0m"
}

left="${1:-}"
if [ -z "$left" ]; then
    left=$(git for-each-ref --format='%(upstream:short)' "$(git symbolic-ref -q HEAD)")
fi

right="${2:-}"
if [ -z "$right" ]; then
    right=HEAD
fi

help "Lines beginning with a < are only in $left"
help "Lines beginning with a > are only in $right"
echo
git log --left-right --cherry-pick "$left...$right"
