#!/bin/sh

# Garbage collect all - https://stackoverflow.com/a/14728706
exec git \
    -c gc.reflogExpire=0 \
    -c gc.reflogExpireUnreachable=0 \
    -c gc.rerereresolved=0 \
    -c gc.rerereunresolved=0 \
    -c gc.pruneExpire=now \
    gc "$@"
