#!/bin/bash
set -o errexit -o nounset -o pipefail

if command -v jq &>/dev/null; then
    curl -fsS https://ipinfo.io/ | jq
else
    curl https://ipinfo.io/
    echo # Add missing trailing new line
fi
