#!/bin/bash

root=$(pwd 2>/dev/null)
while [ ! -e "$root/script/rails" ]; do
    if [ "$root" = "" ]; then
        echo "Not inside a Rails application" >&2
        exit 1
    fi
    root=${root%/*}
done

exec pry -r ./config/environment.rb
