#!/bin/bash
set -o errexit -o nounset -o pipefail

# Upgrade tmux from 1.8 to 2.x
# https://pkgs.org/search/?q=tmux
sudo yum remove -y tmux
sudo yum install -y https://repo.ius.io/archive/7/x86_64/packages/t/tmux2u-2.8-1.ius.el7.x86_64.rpm
