#!/bin/bash

if [ $# -lt 1 ]; then
    echo "Usage: $(basename "$0") <repo>" >&2
    exit 1
fi

#TMPDIR=$(mktemp -d)
#mkdir $TMPDIR/{trunk,branches,tags,sandbox}
#
#svn import $TMPDIR "$1" -m "Initialize repository layout"
#
#rm -rf $TMPDIR

repo=${1%/}
svn mkdir -m "Initialize repository layout" "$repo/trunk" "$repo/branches" "$repo/tags"
